services:
    proxyWEB:
        image: proxyimage:1.0.0
        container_name: proxy
        ports:
          - "8002:80"
        volumes:
          - ./proxy-site:/srv/www
          - ./apache2.conf:/etc/apache2/apache2.conf
        networks:
           proxy-net:
               ipv4_address: 172.18.0.2
        deploy:
          resources:
            limits:
              cpus: '0.1'
              memory: 4096M
networks:
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
